-- =====================================================
-- Seed: 006_notification_templates.sql
-- Purpose: Templates de notification (71 templates)
-- Date: 2025-12-24
-- Ref: PRD 03 - Système de notifications
-- =====================================================

-- Templates Authentification (5)
INSERT INTO notification_templates (code_template, canal, sujet, corps, variables_json, actif) VALUES
('AUTH_BIENVENUE', 'Email', 'Bienvenue sur CheckMaster', 'Bonjour {{nom}},\n\nVotre compte CheckMaster a été créé.\n\nLogin: {{email}}\n\nCliquez sur le lien suivant pour définir votre mot de passe: {{lien_activation}}\n\nCe lien expire dans 48 heures.\n\nCordialement,\nL''équipe CheckMaster', '{"nom": "string", "email": "string", "lien_activation": "string"}', TRUE),
('AUTH_RESET_PASSWORD', 'Email', 'Réinitialisation de mot de passe', 'Bonjour {{nom}},\n\nUne demande de réinitialisation de mot de passe a été effectuée.\n\nCliquez sur ce lien pour réinitialiser: {{lien}}\n\nCe lien expire dans 24 heures.\n\nSi vous n''êtes pas à l''origine de cette demande, ignorez cet email.', '{"nom": "string", "lien": "string"}', TRUE),
('AUTH_PASSWORD_CHANGED', 'Email', 'Mot de passe modifié', 'Bonjour {{nom}},\n\nVotre mot de passe a été modifié avec succès.\n\nSi vous n''êtes pas à l''origine de cette modification, contactez immédiatement l''administrateur.', '{"nom": "string"}', TRUE),
('AUTH_SESSION_FORCEE', 'Email', 'Session terminée', 'Bonjour {{nom}},\n\nVotre session a été fermée par un administrateur.\n\nRaison: {{raison}}\n\nSi vous avez des questions, contactez le support.', '{"nom": "string", "raison": "string"}', TRUE),
('AUTH_TENTATIVES_ECHEC', 'Email', 'Alertes de sécurité - Tentatives échouées', 'Bonjour {{nom}},\n\nNous avons détecté {{nombre}} tentatives de connexion échouées sur votre compte.\n\nDernière tentative: {{date}} depuis {{ip}}\n\nSi ce n''était pas vous, changez votre mot de passe immédiatement.', '{"nom": "string", "nombre": "integer", "date": "string", "ip": "string"}', TRUE)
ON DUPLICATE KEY UPDATE sujet = VALUES(sujet), corps = VALUES(corps), variables_json = VALUES(variables_json), actif = VALUES(actif);

-- Templates Candidature (8)
INSERT INTO notification_templates (code_template, canal, sujet, corps, variables_json, actif) VALUES
('CANDIDATURE_SOUMISE', 'Email', 'Candidature soumise', 'Bonjour {{nom}},\n\nVotre candidature a été soumise avec succès.\n\nThème: {{theme}}\nEntreprise: {{entreprise}}\nDate de soumission: {{date}}\n\nVotre candidature sera examinée par le service scolarité.', '{"nom": "string", "theme": "string", "entreprise": "string", "date": "string"}', TRUE),
('CANDIDATURE_VALIDEE', 'Email', 'Candidature validée', 'Bonjour {{nom}},\n\nVotre candidature a été validée par le service scolarité.\n\nThème: {{theme}}\n\nVous pouvez maintenant procéder au paiement des frais de scolarité.', '{"nom": "string", "theme": "string"}', TRUE),
('CANDIDATURE_REJETEE', 'Email', 'Candidature rejetée', 'Bonjour {{nom}},\n\nVotre candidature a été rejetée.\n\nMotif: {{motif}}\n\nVous pouvez soumettre une nouvelle candidature après correction.', '{"nom": "string", "motif": "string"}', TRUE),
('CANDIDATURE_DEMANDE_INFO', 'Email', 'Informations complémentaires requises', 'Bonjour {{nom}},\n\nDes informations complémentaires sont requises pour votre candidature.\n\n{{message}}\n\nMerci de compléter votre dossier dans les plus brefs délais.', '{"nom": "string", "message": "string"}', TRUE),
('CANDIDATURE_RAPPEL', 'Email', 'Rappel - Candidature en attente', 'Bonjour {{nom}},\n\nVotre candidature est en attente depuis {{jours}} jours.\n\nÉtat actuel: {{etat}}\n\nAction requise: {{action}}', '{"nom": "string", "jours": "integer", "etat": "string", "action": "string"}', TRUE),
('CANDIDATURE_VALIDATION_SCOLARITE', 'Email', 'Nouvelle candidature à valider', 'Bonjour,\n\nUne nouvelle candidature nécessite votre validation.\n\nÉtudiant: {{etudiant}}\nThème: {{theme}}\n\nConnectez-vous pour traiter cette demande.', '{"etudiant": "string", "theme": "string"}', TRUE),
('CANDIDATURE_FORMAT_VALIDE', 'Email', 'Format de rapport validé', 'Bonjour {{nom}},\n\nLe format de votre rapport a été validé par le service communication.\n\nVotre dossier est maintenant en attente d''évaluation par la commission.', '{"nom": "string"}', TRUE),
('CANDIDATURE_FORMAT_REJETE', 'Email', 'Format de rapport à corriger', 'Bonjour {{nom}},\n\nLe format de votre rapport nécessite des corrections.\n\nCommentaires: {{commentaires}}\n\nMerci de corriger et resoumettre.', '{"nom": "string", "commentaires": "string"}', TRUE)
ON DUPLICATE KEY UPDATE sujet = VALUES(sujet), corps = VALUES(corps), variables_json = VALUES(variables_json), actif = VALUES(actif);

-- Templates Paiement (7)
INSERT INTO notification_templates (code_template, canal, sujet, corps, variables_json, actif) VALUES
('PAIEMENT_RECU', 'Email', 'Paiement reçu', 'Bonjour {{nom}},\n\nNous avons bien reçu votre paiement.\n\nMontant: {{montant}} FCFA\nRéférence: {{reference}}\nDate: {{date}}\n\nVotre reçu est disponible dans votre espace étudiant.', '{"nom": "string", "montant": "decimal", "reference": "string", "date": "string"}', TRUE),
('PAIEMENT_COMPLET', 'Email', 'Paiement complet - Dossier débloqué', 'Bonjour {{nom}},\n\nVotre paiement est maintenant complet.\n\nTotal payé: {{total}} FCFA\n\nVotre dossier a été débloqué pour la suite du processus.', '{"nom": "string", "total": "decimal"}', TRUE),
('PAIEMENT_RAPPEL', 'Email', 'Rappel de paiement', 'Bonjour {{nom}},\n\nVous avez un solde impayé de {{solde}} FCFA.\n\nDate limite: {{date_limite}}\n\nMerci de régulariser votre situation.', '{"nom": "string", "solde": "decimal", "date_limite": "string"}', TRUE),
('PAIEMENT_RETARD', 'Email', 'Paiement en retard - Pénalité appliquée', 'Bonjour {{nom}},\n\nVotre paiement est en retard de {{jours}} jours.\n\nUne pénalité de {{penalite}} FCFA a été appliquée.\n\nNouveau total: {{total}} FCFA', '{"nom": "string", "jours": "integer", "penalite": "decimal", "total": "decimal"}', TRUE),
('PAIEMENT_EXONERATION', 'Email', 'Exonération accordée', 'Bonjour {{nom}},\n\nUne exonération de {{montant}} FCFA ({{pourcentage}}%) vous a été accordée.\n\nMotif: {{motif}}\n\nNouveau montant dû: {{nouveau_total}} FCFA', '{"nom": "string", "montant": "decimal", "pourcentage": "decimal", "motif": "string", "nouveau_total": "decimal"}', TRUE),
('RECU_DISPONIBLE', 'Email', 'Reçu de paiement disponible', 'Bonjour {{nom}},\n\nVotre reçu de paiement est disponible.\n\nRéférence: {{reference}}\nMontant: {{montant}} FCFA\n\nTéléchargez-le depuis votre espace étudiant.', '{"nom": "string", "reference": "string", "montant": "decimal"}', TRUE),
('PAIEMENT_NOTIFICATION_SCOLARITE', 'Email', 'Nouveau paiement enregistré', 'Bonjour,\n\nUn nouveau paiement a été enregistré.\n\nÉtudiant: {{etudiant}}\nMontant: {{montant}} FCFA\nMode: {{mode}}', '{"etudiant": "string", "montant": "decimal", "mode": "string"}', TRUE)
ON DUPLICATE KEY UPDATE sujet = VALUES(sujet), corps = VALUES(corps), variables_json = VALUES(variables_json), actif = VALUES(actif);

-- Templates Commission (10)
INSERT INTO notification_templates (code_template, canal, sujet, corps, variables_json, actif) VALUES
('COMMISSION_SESSION_PLANIFIEE', 'Email', 'Session de commission planifiée', 'Bonjour {{nom}},\n\nUne session de commission a été planifiée.\n\nDate: {{date}}\nLieu: {{lieu}}\nNombre de rapports: {{nombre_rapports}}\n\nMerci de confirmer votre présence.', '{"nom": "string", "date": "string", "lieu": "string", "nombre_rapports": "integer"}', TRUE),
('COMMISSION_RAPPEL_SESSION', 'Email', 'Rappel - Session de commission demain', 'Bonjour {{nom}},\n\nRappel: Session de commission demain.\n\nDate: {{date}}\nLieu: {{lieu}}\n\nN''oubliez pas de consulter les rapports à évaluer.', '{"nom": "string", "date": "string", "lieu": "string"}', TRUE),
('COMMISSION_RAPPORT_ATTRIBUE', 'Email', 'Rapport attribué pour évaluation', 'Bonjour {{nom}},\n\nUn rapport vous a été attribué pour évaluation.\n\nÉtudiant: {{etudiant}}\nThème: {{theme}}\nSession: {{date_session}}\n\nConsultez le rapport dans votre espace.', '{"nom": "string", "etudiant": "string", "theme": "string", "date_session": "string"}', TRUE),
('COMMISSION_VOTE_ENREGISTRE', 'Email', 'Vote enregistré', 'Bonjour {{nom}},\n\nVotre vote a été enregistré avec succès.\n\nRapport: {{rapport}}\nDécision: {{decision}}\nTour: {{tour}}', '{"nom": "string", "rapport": "string", "decision": "string", "tour": "integer"}', TRUE),
('COMMISSION_RAPPORT_VALIDE', 'Email', 'Rapport validé par la commission', 'Bonjour {{nom}},\n\nVotre rapport a été validé par la commission.\n\nRésultat: Approuvé à l''unanimité\nTour de vote: {{tour}}\n\nVotre dossier passe maintenant à l''étape suivante.', '{"nom": "string", "tour": "integer"}', TRUE),
('COMMISSION_RAPPORT_A_REVOIR', 'Email', 'Rapport à réviser', 'Bonjour {{nom}},\n\nLa commission demande des modifications sur votre rapport.\n\nCommentaires:\n{{commentaires}}\n\nMerci de procéder aux corrections et resoumettre.', '{"nom": "string", "commentaires": "string"}', TRUE),
('COMMISSION_RAPPORT_REJETE', 'Email', 'Rapport rejeté par la commission', 'Bonjour {{nom}},\n\nVotre rapport a été rejeté par la commission.\n\nMotifs:\n{{motifs}}\n\nVous pouvez soumettre un nouveau rapport après corrections majeures.', '{"nom": "string", "motifs": "string"}', TRUE),
('COMMISSION_PV_DISPONIBLE', 'Email', 'PV de commission disponible', 'Bonjour,\n\nLe PV de la session de commission est disponible.\n\nDate session: {{date}}\nRapports traités: {{nombre}}\n\nConsultez-le dans la section archives.', '{"date": "string", "nombre": "integer"}', TRUE),
('COMMISSION_MEDIATION_REQUISE', 'Email', 'Médiation requise - Vote non unanime', 'Bonjour,\n\nUne médiation du Doyen est requise.\n\nRapport: {{rapport}}\nÉtudiant: {{etudiant}}\nTours effectués: {{tours}}\n\nMerci de traiter cette escalade.', '{"rapport": "string", "etudiant": "string", "tours": "integer"}', TRUE),
('COMMISSION_DECISION_FINALE', 'Email', 'Décision finale de la commission', 'Bonjour {{nom}},\n\nLa décision finale concernant votre rapport:\n\nDécision: {{decision}}\nCommentaires: {{commentaires}}\n\n{{prochaines_etapes}}', '{"nom": "string", "decision": "string", "commentaires": "string", "prochaines_etapes": "string"}', TRUE)
ON DUPLICATE KEY UPDATE sujet = VALUES(sujet), corps = VALUES(corps), variables_json = VALUES(variables_json), actif = VALUES(actif);

-- Templates Encadrement (6)
INSERT INTO notification_templates (code_template, canal, sujet, corps, variables_json, actif) VALUES
('ENCADREUR_ASSIGNATION', 'Email', 'Nouvelle assignation d''étudiant', 'Bonjour {{nom}},\n\nVous avez été assigné comme encadreur pédagogique.\n\nÉtudiant: {{etudiant}}\nThème: {{theme}}\n\nConsultez le dossier dans votre espace.', '{"nom": "string", "etudiant": "string", "theme": "string"}', TRUE),
('ENCADREUR_DEMANDE_AVIS', 'Email', 'Avis requis sur dossier étudiant', 'Bonjour {{nom}},\n\nVotre avis est requis sur le dossier suivant:\n\nÉtudiant: {{etudiant}}\nThème: {{theme}}\n\nMerci de donner votre avis dans les 7 jours.', '{"nom": "string", "etudiant": "string", "theme": "string"}', TRUE),
('ENCADREUR_RAPPEL_AVIS', 'Email', 'Rappel - Avis en attente', 'Bonjour {{nom}},\n\nRappel: Un avis est en attente depuis {{jours}} jours.\n\nÉtudiant: {{etudiant}}\n\nMerci de traiter cette demande.', '{"nom": "string", "jours": "integer", "etudiant": "string"}', TRUE),
('ETUDIANT_AVIS_FAVORABLE', 'Email', 'Avis favorable de l''encadreur', 'Bonjour {{nom}},\n\nVotre encadreur pédagogique a donné un avis favorable.\n\nCommentaires: {{commentaires}}\n\nVotre dossier passe à l''étape de constitution du jury.', '{"nom": "string", "commentaires": "string"}', TRUE),
('ETUDIANT_AVIS_DEFAVORABLE', 'Email', 'Avis défavorable de l''encadreur', 'Bonjour {{nom}},\n\nVotre encadreur pédagogique a émis des réserves.\n\nCommentaires: {{commentaires}}\n\nMerci de prendre contact avec votre encadreur.', '{"nom": "string", "commentaires": "string"}', TRUE),
('DIRECTEUR_MEMOIRE_NOTIFICATION', 'Email', 'Notification de direction de mémoire', 'Bonjour {{nom}},\n\nVous êtes enregistré comme directeur de mémoire.\n\nÉtudiant: {{etudiant}}\nThème: {{theme}}\n\nConnectez-vous pour suivre l''avancement.', '{"nom": "string", "etudiant": "string", "theme": "string"}', TRUE)
ON DUPLICATE KEY UPDATE sujet = VALUES(sujet), corps = VALUES(corps), variables_json = VALUES(variables_json), actif = VALUES(actif);

-- Templates Jury et Soutenance (15)
INSERT INTO notification_templates (code_template, canal, sujet, corps, variables_json, actif) VALUES
('JURY_INVITATION', 'Email', 'Invitation à participer à un jury', 'Bonjour {{nom}},\n\nVous êtes invité à participer à un jury de soutenance.\n\nÉtudiant: {{etudiant}}\nThème: {{theme}}\nRôle proposé: {{role}}\n\nMerci de confirmer votre disponibilité.', '{"nom": "string", "etudiant": "string", "theme": "string", "role": "string"}', TRUE),
('JURY_ACCEPTATION', 'Email', 'Participation au jury confirmée', 'Bonjour {{nom}},\n\nVotre participation au jury a été confirmée.\n\nÉtudiant: {{etudiant}}\nRôle: {{role}}\n\nVous serez notifié de la date de soutenance.', '{"nom": "string", "etudiant": "string", "role": "string"}', TRUE),
('JURY_REFUS', 'Email', 'Participation au jury déclinée', 'Bonjour,\n\n{{membre}} a décliné l''invitation au jury.\n\nÉtudiant: {{etudiant}}\nRaison: {{raison}}\n\nVeuillez trouver un remplaçant.', '{"membre": "string", "etudiant": "string", "raison": "string"}', TRUE),
('JURY_COMPLET', 'Email', 'Jury constitué', 'Bonjour {{nom}},\n\nLe jury pour votre soutenance est maintenant complet.\n\nPrésident: {{president}}\nMembres: {{membres}}\n\nLa date de soutenance vous sera communiquée prochainement.', '{"nom": "string", "president": "string", "membres": "string"}', TRUE),
('SOUTENANCE_PLANIFIEE', 'Email', 'Soutenance planifiée', 'Bonjour {{nom}},\n\nVotre soutenance a été planifiée.\n\nDate: {{date}}\nHeure: {{heure}}\nSalle: {{salle}}\n\nMerci de vous présenter 15 minutes avant.', '{"nom": "string", "date": "string", "heure": "string", "salle": "string"}', TRUE),
('SOUTENANCE_RAPPEL_J7', 'Email', 'Rappel soutenance dans 7 jours', 'Bonjour {{nom}},\n\nRappel: Votre soutenance est dans 7 jours.\n\nDate: {{date}}\nSalle: {{salle}}\n\nPréparez votre présentation.', '{"nom": "string", "date": "string", "salle": "string"}', TRUE),
('SOUTENANCE_RAPPEL_J1', 'Email', 'Rappel soutenance demain', 'Bonjour {{nom}},\n\nRappel: Votre soutenance est demain.\n\nDate: {{date}}\nHeure: {{heure}}\nSalle: {{salle}}\n\nBonne chance!', '{"nom": "string", "date": "string", "heure": "string", "salle": "string"}', TRUE),
('SOUTENANCE_CONVOCATION', 'Email', 'Convocation officielle à la soutenance', 'Bonjour {{nom}},\n\nVeuillez trouver ci-joint votre convocation officielle.\n\nDate: {{date}}\nHeure: {{heure}}\nSalle: {{salle}}\n\nDocument à présenter le jour de la soutenance.', '{"nom": "string", "date": "string", "heure": "string", "salle": "string"}', TRUE),
('SOUTENANCE_CODE_PRESIDENT', 'Email', 'Code de démarrage soutenance', 'Bonjour {{nom}},\n\nVoici le code de démarrage pour la soutenance:\n\nCode: {{code}}\nValide de: {{heure_debut}} à {{heure_fin}}\n\nÉtudiant: {{etudiant}}\n\nCe code est strictement personnel.', '{"nom": "string", "code": "string", "heure_debut": "string", "heure_fin": "string", "etudiant": "string"}', TRUE),
('SOUTENANCE_DEMARREE', 'Email', 'Soutenance démarrée', 'Information: La soutenance de {{etudiant}} a démarré.\n\nPrésident: {{president}}\nHeure de début: {{heure}}', '{"etudiant": "string", "president": "string", "heure": "string"}', TRUE),
('SOUTENANCE_TERMINEE', 'Email', 'Soutenance terminée', 'Bonjour {{nom}},\n\nVotre soutenance est terminée.\n\nLes résultats vous seront communiqués après délibération du jury.', '{"nom": "string"}', TRUE),
('SOUTENANCE_REPORTEE', 'Email', 'Soutenance reportée', 'Bonjour {{nom}},\n\nVotre soutenance a été reportée.\n\nAncienne date: {{ancienne_date}}\nNouvelle date: {{nouvelle_date}}\nRaison: {{raison}}', '{"nom": "string", "ancienne_date": "string", "nouvelle_date": "string", "raison": "string"}', TRUE),
('SOUTENANCE_ANNULEE', 'Email', 'Soutenance annulée', 'Bonjour {{nom}},\n\nVotre soutenance a été annulée.\n\nRaison: {{raison}}\n\nVous serez contacté pour reprogrammer.', '{"nom": "string", "raison": "string"}', TRUE),
('JURY_NOTES_SAISIES', 'Email', 'Notes de soutenance enregistrées', 'Bonjour,\n\nLes notes ont été enregistrées pour la soutenance.\n\nÉtudiant: {{etudiant}}\nMention: {{mention}}\nPV généré: {{pv_genere}}', '{"etudiant": "string", "mention": "string", "pv_genere": "boolean"}', TRUE),
('RESULTAT_SOUTENANCE', 'Email', 'Résultat de votre soutenance', 'Bonjour {{nom}},\n\nVoici le résultat de votre soutenance:\n\nNote finale: {{note}}/20\nMention: {{mention}}\nDécision: {{decision}}\n\n{{commentaires}}\n\nFélicitations!', '{"nom": "string", "note": "decimal", "mention": "string", "decision": "string", "commentaires": "string"}', TRUE)
ON DUPLICATE KEY UPDATE sujet = VALUES(sujet), corps = VALUES(corps), variables_json = VALUES(variables_json), actif = VALUES(actif);

-- Templates Workflow et SLA (8)
INSERT INTO notification_templates (code_template, canal, sujet, corps, variables_json, actif) VALUES
('WORKFLOW_TRANSITION', 'Email', 'Changement d''état de votre dossier', 'Bonjour {{nom}},\n\nVotre dossier a changé d''état.\n\nNouvel état: {{etat}}\nDate: {{date}}\n\nProchaine étape: {{prochaine_etape}}', '{"nom": "string", "etat": "string", "date": "string", "prochaine_etape": "string"}', TRUE),
('WORKFLOW_SLA_50', 'Email', 'Alerte SLA - 50% du délai écoulé', 'Attention,\n\nUn dossier atteint 50% de son délai.\n\nÉtudiant: {{etudiant}}\nÉtat: {{etat}}\nDélai restant: {{jours_restants}} jours', '{"etudiant": "string", "etat": "string", "jours_restants": "integer"}', TRUE),
('WORKFLOW_SLA_80', 'Email', 'Alerte SLA urgente - 80% du délai', 'URGENT,\n\nUn dossier atteint 80% de son délai.\n\nÉtudiant: {{etudiant}}\nÉtat: {{etat}}\nDélai restant: {{jours_restants}} jours\n\nAction immédiate requise.', '{"etudiant": "string", "etat": "string", "jours_restants": "integer"}', TRUE),
('WORKFLOW_SLA_100', 'Email', 'CRITIQUE - Délai SLA dépassé', 'CRITIQUE,\n\nUn dossier a dépassé son délai SLA.\n\nÉtudiant: {{etudiant}}\nÉtat: {{etat}}\nDépassement: {{jours_depassement}} jours\n\nEscalade automatique effectuée.', '{"etudiant": "string", "etat": "string", "jours_depassement": "integer"}', TRUE),
('ESCALADE_NIVEAU_1', 'Email', 'Escalade niveau 1 - Responsable niveau', 'Bonjour,\n\nUn dossier vous a été escaladé.\n\nÉtudiant: {{etudiant}}\nProblème: {{probleme}}\nDélai de réponse: 3 jours', '{"etudiant": "string", "probleme": "string"}', TRUE),
('ESCALADE_NIVEAU_2', 'Email', 'Escalade niveau 2 - Responsable filière', 'Bonjour,\n\nUn dossier vous a été escaladé (niveau 2).\n\nÉtudiant: {{etudiant}}\nProblème: {{probleme}}\nHistorique: {{historique}}', '{"etudiant": "string", "probleme": "string", "historique": "string"}', TRUE),
('ESCALADE_NIVEAU_3', 'Email', 'Escalade niveau 3 - Directeur adjoint', 'Bonjour,\n\nUn dossier critique vous a été escaladé.\n\nÉtudiant: {{etudiant}}\nProblème: {{probleme}}\nNiveaux franchis: 2\nUrgence: HAUTE', '{"etudiant": "string", "probleme": "string"}', TRUE),
('ESCALADE_DOYEN', 'Email', 'Escalade Doyen - Médiation requise', 'Monsieur le Doyen,\n\nVotre médiation est requise.\n\nÉtudiant: {{etudiant}}\nProblème: {{probleme}}\nNiveaux franchis: 3\nHistorique complet: {{historique}}', '{"etudiant": "string", "probleme": "string", "historique": "string"}', TRUE)
ON DUPLICATE KEY UPDATE sujet = VALUES(sujet), corps = VALUES(corps), variables_json = VALUES(variables_json), actif = VALUES(actif);

-- Templates Réclamations (5)
INSERT INTO notification_templates (code_template, canal, sujet, corps, variables_json, actif) VALUES
('RECLAMATION_DEPOSEE', 'Email', 'Réclamation déposée', 'Bonjour {{nom}},\n\nVotre réclamation a été enregistrée.\n\nNuméro: {{numero}}\nObjet: {{objet}}\n\nVous recevrez une réponse sous 5 jours ouvrés.', '{"nom": "string", "numero": "string", "objet": "string"}', TRUE),
('RECLAMATION_EN_COURS', 'Email', 'Réclamation en cours de traitement', 'Bonjour {{nom}},\n\nVotre réclamation est en cours de traitement.\n\nNuméro: {{numero}}\nAssignée à: {{responsable}}', '{"nom": "string", "numero": "string", "responsable": "string"}', TRUE),
('RECLAMATION_REPONSE', 'Email', 'Réponse à votre réclamation', 'Bonjour {{nom}},\n\nVoici la réponse à votre réclamation:\n\nNuméro: {{numero}}\nRéponse:\n{{reponse}}\n\nSi vous n''êtes pas satisfait, vous pouvez faire appel.', '{"nom": "string", "numero": "string", "reponse": "string"}', TRUE),
('RECLAMATION_NOUVELLE', 'Email', 'Nouvelle réclamation à traiter', 'Bonjour,\n\nUne nouvelle réclamation nécessite votre attention.\n\nNuméro: {{numero}}\nÉtudiant: {{etudiant}}\nObjet: {{objet}}\nPriorité: {{priorite}}', '{"numero": "string", "etudiant": "string", "objet": "string", "priorite": "string"}', TRUE),
('RECLAMATION_ESCALADEE', 'Email', 'Réclamation escaladée', 'Bonjour,\n\nUne réclamation vous a été escaladée.\n\nNuméro: {{numero}}\nÉtudiant: {{etudiant}}\nMotif escalade: {{motif}}', '{"numero": "string", "etudiant": "string", "motif": "string"}', TRUE)
ON DUPLICATE KEY UPDATE sujet = VALUES(sujet), corps = VALUES(corps), variables_json = VALUES(variables_json), actif = VALUES(actif);

-- Templates Administration (7)
INSERT INTO notification_templates (code_template, canal, sujet, corps, variables_json, actif) VALUES
('ADMIN_MAINTENANCE', 'Email', 'Maintenance planifiée', 'Bonjour,\n\nUne maintenance est planifiée.\n\nDate: {{date}}\nDurée estimée: {{duree}}\nImpact: {{impact}}\n\nMerci de sauvegarder vos travaux en cours.', '{"date": "string", "duree": "string", "impact": "string"}', TRUE),
('ADMIN_BACKUP_COMPLETE', 'Email', 'Sauvegarde complétée', 'Rapport de sauvegarde:\n\nDate: {{date}}\nTaille: {{taille}}\nStatut: {{statut}}\nEmplacement: {{emplacement}}', '{"date": "string", "taille": "string", "statut": "string", "emplacement": "string"}', TRUE),
('ADMIN_BACKUP_ECHEC', 'Email', 'ALERTE - Échec de sauvegarde', 'ALERTE CRITIQUE\n\nLa sauvegarde a échoué.\n\nDate: {{date}}\nErreur: {{erreur}}\n\nAction immédiate requise.', '{"date": "string", "erreur": "string"}', TRUE),
('ADMIN_INTEGRITY_ALERT', 'Email', 'Alerte intégrité des archives', 'ALERTE\n\nUne vérification d''intégrité a échoué.\n\nDocument: {{document}}\nHash attendu: {{hash_attendu}}\nHash trouvé: {{hash_trouve}}', '{"document": "string", "hash_attendu": "string", "hash_trouve": "string"}', TRUE),
('ADMIN_RAPPORT_QUOTIDIEN', 'Email', 'Rapport quotidien CheckMaster', 'Rapport du {{date}}:\n\nNouveaux dossiers: {{nouveaux}}\nSoutenances: {{soutenances}}\nPaiements: {{paiements}} FCFA\nAlertes: {{alertes}}', '{"date": "string", "nouveaux": "integer", "soutenances": "integer", "paiements": "decimal", "alertes": "integer"}', TRUE),
('ADMIN_NOUVELLE_ANNEE', 'Email', 'Nouvelle année académique', 'Information,\n\nL''année académique {{annee}} a été activée.\n\nTous les paramètres ont été mis à jour.\n\nBonne rentrée!', '{"annee": "string"}', TRUE),
('ADMIN_IMPORT_TERMINE', 'Email', 'Import de données terminé', 'Import terminé:\n\nType: {{type}}\nLignes traitées: {{total}}\nRéussies: {{reussies}}\nErreurs: {{erreurs}}\n\nVoir le rapport détaillé.', '{"type": "string", "total": "integer", "reussies": "integer", "erreurs": "integer"}', TRUE)
ON DUPLICATE KEY UPDATE sujet = VALUES(sujet), corps = VALUES(corps), variables_json = VALUES(variables_json), actif = VALUES(actif);
